name: 'Update Keymap README'

on:
  push:
    branches:
      - main
    paths:
      - 'config/microball.keymap'
      - 'config/microball.json'
      - '.github/scripts/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '.github/scripts/package.json'
          
      - name: Install dependencies
        working-directory: .github/scripts
        run: npm ci
        
      - name: Build TypeScript
        working-directory: .github/scripts
        run: npm run build
        
      - name: Update README.md
        working-directory: .github/scripts
        run: npm run start
        
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: keymap-pdf
          path: keymap.pdf
          retention-days: 90
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📝 Update keymap README.md [skip ci]"
            git push
          fi
